# Generated by Django 5.1.1 on 2024-11-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_plate', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(default='Checking', max_length=50)),
                ('tracking_number', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='backend.truck')),
            ],
        ),
    ]
