# Generated by Django 5.1.1 on 2024-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_truck_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='tracking_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_plate',
            field=models.CharField(max_length=255),
        ),
    ]
