# Generated by Django 5.1.1 on 2024-11-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_truck_status_alter_truck_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='checkpoint_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='checkpoint_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='checkpoint_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='checkpoint_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='checkpoint_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='tracking_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
