# Generated by Django 5.1.1 on 2024-11-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_location_truck_checkpoint_1_truck_checkpoint_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
