# Generated by Django 5.1.1 on 2024-11-20 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_order_status_alter_order_truck_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
