# Generated by Django 5.1.1 on 2024-11-20 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_coordinates_updated_at_coordinates_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='order_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
