# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - CKLogistics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd logistics
          pip install -r requirements.txt

      - name: startup command
        env:
          MAPBOX: "${{ secrets.MAPBOX }}"
          DATABASECREDS: "${{ secrets.DATABASECREDS }}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          DEBUG: "True"
        run: |
          cd logistics
          python manage.py check
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
           cd logistics
           zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19DDD3B60B2648E399CFA998CE947F78 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AA0D7B198B84952B5F05CAEF9B5D2B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D83E5E95FAB9427191B6BD0A2860807E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CKLogistics'
          slot-name: 'Production'
          
